# https://qiita.com/omukaik/items/b0e88dd8540798d9252c
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vngb-app-backend
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run dev:debug
    expose:
      - 80
      - 9229
    ports:
      - 3000:80
      - 9229:9229
