name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ECR_REPO_NAME: vngb-v2-ecr-repo
  ECS_CLUSTER_NAME: vngb-v2-ecs-cluster
  ECS_SERVICE_NAME: vngb-v2-ecs-service
  ECS_TASK_DEFINITION_FAMILY: .aws/task-definition.json
  CONTAINER_NAME: vngb-v2-ecs-container
  APPSPEC_FILE: .aws/appspec.yml
  CODEDEPLOY_APP_NAME: vngb-v2-codedeploy-app
  CODEDEPLOY_DEPLOYMENT_GROUP: vngb-v2-codedeploy-deployment-group

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      task-definition: ${{ steps.task-definition.outputs.task-definition }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # tag: GITHUB_REF##*/=v1.0.0
      - name: Create tag
        id: create-tag
        run: |
          [[ -z "${GITHUB_REF##*/} = v*" ]] && "TAG=${GITHUB_REF##*/}" || TAG=`date +v%Y%m%d`-${GITHUB_SHA::8}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

        # docker/build-push-action@v5の処理でbuildxに依存しているため、前段でこのactionsを実行
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        id: build-image
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ steps.create-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          platforms: linux/arm64

      - name: Create ECS task definition
        id: task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_FAMILY }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ steps.create-tag.outputs.tag }}

      - name: deploy to ecs
        id: deploy-to-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          # inputs: https://github.com/aws-actions/amazon-ecs-deploy-task-definition/blob/master/action.yml
          task-definition: ${{ steps.task-definition.outputs.task-definition }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          service: ${{ env.ECS_SERVICE_NAME }}
          codedeploy-appspec: ${{ env.APPSPEC_FILE }}
          codedeploy-application: ${{ env.CODEDEPLOY_APP_NAME }}
          codedeploy-deployment-group: ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }}
