name: Create PR from main

on:
  push:
    branches:
      - main
# 将来的にpathsを指定して、アプリケーションのファイルが変更された時のみ実行するようにする

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Token
        id: get_token
        run: echo "::set-output name=token::${{ secrets.GITHUB_TOKEN }}"

      - name: Create PR
        id: create_pr
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
          BASE_BRANCH: development
          HEAD_BRANCH: main
        shell: bash
        run: |
          PR_URL_DEV=$(gh pr create -B ${{ env.BASE_BRANCH }} -H ${{ env.HEAD_BRANCH}} -l ${{ env.BASE_BRANCH}} -t "${{ env.BASE_BRANCH }} <- ${{ env.HEAD_BRANCH }}" -b "This PR is created automatically from ${{ env.HEAD_BRANCH }} to ${{ env.BASE_BRANCH }}.")
          echo "PR_URL_DEV=${PR_URL_DEV}" >> $GITHUB_OUTPUT
        continue-on-error: true
